apiVersion: v1
kind: Service
metadata:
  name: node-rest-lb
  labels:
    service: node-rest-lb
spec:
  selector:
    app: nagp-sa-webapi
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 30368