apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-sa-webapi-deployment
  labels:
    name: nagp-sa-webapi-2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nagp-sa-webapi
  template:
    metadata:
      labels:
        app: nagp-sa-webapi
    spec:
      containers:
      - name: nagp-sa-webapi
        image: theaggarwal/nagp-sa:5
        ports:
        - containerPort: 3001
        env:
            - name: dburl
              valueFrom:
                configMapKeyRef:
                  name: node-config
                  key: db.string
            - name: dbname
              valueFrom:
                configMapKeyRef:
                  name: node-config
                  key: db.name
            - name: dbuser
              valueFrom:
                secretKeyRef:
                  name: node-creds
                  key: username
            - name: dbpassword
              valueFrom:
                secretKeyRef:
                  name: node-creds
                  key: password
